application: gulimuvisualization
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: app.view.index.app

- url: /weibo
  script: app.view.weibo.app

- url: /weibo/.*
  script: app.view.weibo.app

- url: /(.*\.txt)
  static_files: static/misc/\1
  upload: static/misc/(.*\.txt)

- url: /static
  static_dir: static

- url: /.*
  script: app.view.notfound.app

libraries:
- name: django
  version: "1.2"